name: Workflow for bumpng semantic version

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: directory to run commands
        required: true
      update-versions-in:
        type: string
        description: "parameter to pass to 'intelygenz/monorepo-tagger-action'"
        required: true
    secrets:
      TOKEN:
        required: true

jobs:
  check:
    uses: ./.github/workflows/_check.yml
    with:
      working-directory: ${{ inputs.working-directory }}

  deploy:
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate a release
        uses: Rindrics/tagpr@monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          TAGPR_CONFIG_PATH: "${{ inputs.working-directory }}/.tagpr"

