name: "[core] Check module"

on:
  pull_request:
    paths:
      core
      !core/**.md

env:
  WORKING_DIRECTORY: core

jobs:
  check-core:
    uses: ./.github/workflows/_check.yml
    with:
      working-directory: ${{ env.WORKING_DIRECTORY }}
